name: dqn_navigation
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - jupyter
  - numpy
  - scipy=1.11.2
  - matplotlib=3.7.2
  - tensorflow
  - pandas=2.0.3
  - Keras
  - seaborn=0.12.2
  - bokeh=3.2.2
  - gensim
  - Theano
  - jupyter
  - scikit-learn=1.3.0
  - Shapely
  - sympy=1.12
  - pip
  - pip:
    - gym==0.24.1
    - mujoco-py
    - torch
    - torchvision
    - -e ./unityagents-0.4.0

